### ISSUE TITLE
区别

### ISSUE THREAD

**Issue by smallCannon** [sing1ee/analyzer-solr#10]
请问 analyzer.solr5.stanford.StanfordTokenizerFactory
analyzer.solr5.jieba.JiebaTokenizerFactory
这两个配置有什么区别吗

**Comment by sing1ee** [comment]
实现不同

2017-10-26 13:23 GMT+08:00 anoteboy <notifications@github.com>:

**Comment by smallCannon** [comment]
谢谢，现在已经在使用，请问有1.0.2对应的版本吗

**Comment by sing1ee** [comment]
这个你可以直接升级，看看是否有不兼容，如果有问题，改一下源码就可以了。

**Comment by smallCannon** [comment]
好的 多谢了
