### ISSUE TITLE
solr使用结巴分词器自定义词典不起效果

### ISSUE THREAD

**Issue by chandlermoon** [sing1ee/analyzer-solr#11]
请教一下，solr想使用结巴分词器自定义词典。配置完之后没有效果。请问会是哪里的问题。 @sing1ee 
![vsuw7er0 y y 0b ndfv k](https://user-images.githubusercontent.com/35758804/35319541-392aba72-011b-11e8-81f2-43870db93a2f.png)
![q m u 0 mdh_btotx_ 8](https://user-images.githubusercontent.com/35758804/35319545-40026ae8-011b-11e8-9bdc-b6b43aa953fb.png)
![tli_evcoi92 ltf222akw](https://user-images.githubusercontent.com/35758804/35319549-434a6b10-011b-11e8-8c97-56a7fa81202c.png)

**Comment by sing1ee** [comment]
文件格式，文件编码，都可以检查一下

**Comment by chandlermoon** [comment]
首先很感谢回复。然后，我检查过UTF-8无BOM格式保存的，依旧不起效果。

**Comment by hupay** [comment]
试了下solr6.2.1可以用，solr8.1.1就不能用了。

**Comment by sing1ee** [comment]
没有做适配，改天更新下。
