### ISSUE TITLE
请问能提供Licence吗？

### ISSUE THREAD

**Issue by jzhao166** [sing1ee/analyzer-solr#13]
您好，我是Bloomberg L.P. 的工程师，请问我们能使用您的这份代码吗？如果可以的话，能请您上传一份Licence文件吗？谢谢。

**Comment by sing1ee** [comment]
可以的，马上操作。

jzhao166 <notifications@github.com> 于2018年9月1日周六 上午2:14写道：

**Comment by jzhao166** [comment]
谢谢您！
