### ISSUE TITLE
在solr admin用analysis出現訊息

### ISSUE THREAD

**Issue by cklong2k** [sing1ee/analyzer-solr#3]
solr 5.3.1
analysis的FieldType: text_jieba
出現訊息
java.lang.NoClassDefFoundError: com/huaban/analysis/jieba/WordDictionary

請問該如解決？

**Comment by sing1ee** [comment]
这个应该是 com.huaban:jieba-analysis:1.0.0 没有找到。build的时候，有这个么？

**Comment by cklong2k** [comment]
先謝謝你的回答
build.gradle
compile("org.apache.lucene:lucene-core:5.3.1")
compile("org.apache.lucene:lucene-queryparser:5.3.1")
compile("org.apache.lucene:lucene-analyzers-common:5.3.1")
compile('com.huaban:jieba-analysis:1.0.0')
compile("edu.stanford.nlp:stanford-corenlp:3.5.2")

錯誤訊息
warning: [options] bootstrap class path not set in conjunction with -source 1.5
warning: /home/cklong2k/.gradle/caches/artifacts-23/filestore/edu.stanford.nlp/stanford-corenlp/3.5.2/jar/1d5d0876de963c41ebf39d1d5570972ca7b592b4/stanford-corenlp-3.5.2.jar(edu/stanford/nlp/ie/crf/CRFClassifier.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: /home/cklong2k/.gradle/caches/artifacts-23/filestore/edu.stanford.nlp/stanford-corenlp/3.5.2/jar/1d5d0876de963c41ebf39d1d5570972ca7b592b4/stanford-corenlp-3.5.2.jar(edu/stanford/nlp/ling/CoreLabel.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
/home/cklong2k/analyzer-solr/src/main/java/analyzer/solr5/stanford/StanfordAdapter.java:19: error: StanfordAdapter is not abstract and does not override abstract method remove() in Iterator
public class StanfordAdapter implements Iterator<String> {
       ^
warning: /home/cklong2k/.gradle/caches/artifacts-23/filestore/edu.stanford.nlp/stanford-corenlp/3.5.2/jar/1d5d0876de963c41ebf39d1d5570972ca7b592b4/stanford-corenlp-3.5.2.jar(edu/stanford/nlp/util/CoreMap.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: /home/cklong2k/.gradle/caches/artifacts-23/filestore/edu.stanford.nlp/stanford-corenlp/3.5.2/jar/1d5d0876de963c41ebf39d1d5570972ca7b592b4/stanford-corenlp-3.5.2.jar(edu/stanford/nlp/util/ArrayCoreMap.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: /home/cklong2k/.gradle/caches/artifacts-23/filestore/edu.stanford.nlp/stanford-corenlp/3.5.2/jar/1d5d0876de963c41ebf39d1d5570972ca7b592b4/stanford-corenlp-3.5.2.jar(edu/stanford/nlp/sequences/SeqClassifierFlags.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: /home/cklong2k/.gradle/caches/artifacts-23/filestore/edu.stanford.nlp/stanford-corenlp/3.5.2/jar/1d5d0876de963c41ebf39d1d5570972ca7b592b4/stanford-corenlp-3.5.2.jar(edu/stanford/nlp/ie/AbstractSequenceClassifier.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: /home/cklong2k/.gradle/caches/artifacts-23/filestore/edu.stanford.nlp/stanford-corenlp/3.5.2/jar/1d5d0876de963c41ebf39d1d5570972ca7b592b4/stanford-corenlp-3.5.2.jar(edu/stanford/nlp/sequences/DocumentReaderAndWriter.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
1 error
8 warnings
:compileJava FAILED

**Comment by cklong2k** [comment]
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u4 (2015-09-19) x86_64 GNU/Linux
JAVA_HOME = /usr/lib/jvm/java-8-oracle
java version "1.8.0_60"
Gradle 2.7
solr 5.3.1

**Comment by sing1ee** [comment]
请问你是 gradle build输出的结果么？以下是我这边的输出

``` shell
 $ gradle build
:compileJava
警告: [options] 未与 -source 1.5 一起设置引导类路径
警告: [options] 源值1.5已过时, 将在未来所有发行版中删除
警告: [options] 目标值1.5已过时, 将在未来所有发行版中删除
警告: [options] 要隐藏有关已过时选项的警告, 请使用 -Xlint:-options。
4 个警告
:processResources UP-TO-DATE
:classes
:jar
:assemble
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:check UP-TO-DATE
:build

BUILD SUCCESSFUL

Total time: 4.229 secs
```

**Comment by sing1ee** [comment]
@ cklong2k 应该是 stanford的库没找到。出错信息好像变了。

**Comment by cklong2k** [comment]
gradle build輸出結果與你相同，請問你怎麼配置analyzer-solr-1.0.jar與classes於solr5？(我是solr新手)

**Comment by sing1ee** [comment]
``` xml

<fieldType name="text_jieba" class="solr.TextField" positionIncrementGap="100">
      <analyzer type="index">
        <tokenizer class="analyzer.solr5.jieba.JiebaTokenizerFactory"  segMode="SEARCH" userDict="/your_path_to_dict.txt"/>
        <filter class="solr.StopFilterFactory" ignoreCase="true" words="stopwords.txt" />
        <filter class="solr.LowerCaseFilterFactory"/>
        <filter class="solr.SnowballPorterFilterFactory" language="English"/>
      </analyzer>
      <analyzer type="query">
        <tokenizer class="analyzer.solr5.jieba.JiebaTokenizerFactory"  segMode="SEARCH" userDict="/your_path_to_dict.txt"/>
        <filter class="solr.StopFilterFactory" ignoreCase="true" words="stopwords.txt" />
        <filter class="solr.SynonymFilterFactory" synonyms="synonyms.txt" ignoreCase="true" expand="true"/>
        <filter class="solr.LowerCaseFilterFactory"/>
        <filter class="solr.SnowballPorterFilterFactory" language="English"/>
      </analyzer>
    </fieldType>

```

首先配置这个，然后把analyzer-solr-1.0.jar 放在像这样的目录里：solr-5.0.0/server/solr-webapp/webapp/WEB-INF/lib

**Comment by cklong2k** [comment]
目前配置是與你相同

**Comment by cklong2k** [comment]
solr-5.3.1/server/solr-webapp/webapp/WEB-INF/lib 我少放了jieba-analysis-1.0.0.jar
目前沒有其他問題，thanks
