### ISSUE TITLE
analyzer-slor中是不是对solr4.X不支持？

### ISSUE THREAD

**Issue by yuanjianfaith** [sing1ee/analyzer-solr#5]
用的jar
analyzer-solr-1.0.jar
jieba-analysis-1.0.2.jar

solr配置文件中按照指定的配置？
在solr查询报错，java.lang.AbstractMethodError

**Comment by yuanjianfaith** [comment]
其中
analysis的FieldType: text_jieba
出現訊息
java.lang.AbstractMethodError

**Comment by sing1ee** [comment]
你可以试试这个：https://github.com/sing1ee/jieba-solr analyzer-solr是5.0的

**Comment by yuanjianfaith** [comment]
太感谢了。
